#################################
## Author: Fernando Melone     ##
## Email: fern.melone@imply.io ##
#################################

#cloud-config
package_update: true
package_upgrade: true

packages:          
 - openjdk-8-jre-headless
 - python

runcmd:
 - curl -LO http://static.imply.io/release/imply-2021.11.tar.gz
 - tar -xzf imply-2021.11.tar.gz -C /home/ubuntu
 - chown -R ubuntu:ubuntu /home/ubuntu
 - cd imply-2021.11
 - /usr/bin/screen -dmS imply /home/ubuntu/imply-2021.11/bin/supervise -c /home/ubuntu/imply-2021.11/conf/supervise/quickstart.conf
